name: Senior Photography By Anthony Davis
favicon: null
layout_spectrum: 0.8439117132220417
typography_spectrum: 0.7881005157250911
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.9296335859689862
  lightness: 0.2841278670821339
  saturation: 0.9593465416692197
  rhythmicContrast: 0.0136548753362149
purpose: []
